/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AppQuizRouteImport } from './routes/_app.quiz'
import { Route as AppPerfilRouteImport } from './routes/_app.perfil'
import { Route as AppHomeRouteImport } from './routes/_app.home'
import { Route as AppCasoRouteImport } from './routes/_app.caso'
import { Route as AppAtlasRouteImport } from './routes/_app.atlas'
import { Route as AdminQuizIndexRouteImport } from './routes/admin.quiz.index'
import { Route as AdminCasosIndexRouteImport } from './routes/admin.casos.index'
import { Route as AdminAtlasIndexRouteImport } from './routes/admin.atlas.index'
import { Route as AppCasoIndexRouteImport } from './routes/_app.caso.index'
import { Route as AppAtlasIndexRouteImport } from './routes/_app.atlas.index'
import { Route as AdminQuizIdRouteImport } from './routes/admin.quiz.$id'
import { Route as AdminCasosIdRouteImport } from './routes/admin.casos.$id'
import { Route as AdminAtlasIdRouteImport } from './routes/admin.atlas.$id'
import { Route as AppCasoIdRouteImport } from './routes/_app.caso.$id'
import { Route as AppAtlasRegionRouteImport } from './routes/_app.atlas.$region'
import { Route as AppAtlasRegionIndexRouteImport } from './routes/_app.atlas.$region.index'
import { Route as AppAtlasRegionStructureRouteImport } from './routes/_app.atlas.$region.$structure'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppQuizRoute = AppQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppCasoRoute = AppCasoRouteImport.update({
  id: '/caso',
  path: '/caso',
  getParentRoute: () => AppRoute,
} as any)
const AppAtlasRoute = AppAtlasRouteImport.update({
  id: '/atlas',
  path: '/atlas',
  getParentRoute: () => AppRoute,
} as any)
const AdminQuizIndexRoute = AdminQuizIndexRouteImport.update({
  id: '/quiz/',
  path: '/quiz/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCasosIndexRoute = AdminCasosIndexRouteImport.update({
  id: '/casos/',
  path: '/casos/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAtlasIndexRoute = AdminAtlasIndexRouteImport.update({
  id: '/atlas/',
  path: '/atlas/',
  getParentRoute: () => AdminRoute,
} as any)
const AppCasoIndexRoute = AppCasoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCasoRoute,
} as any)
const AppAtlasIndexRoute = AppAtlasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAtlasRoute,
} as any)
const AdminQuizIdRoute = AdminQuizIdRouteImport.update({
  id: '/quiz/$id',
  path: '/quiz/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCasosIdRoute = AdminCasosIdRouteImport.update({
  id: '/casos/$id',
  path: '/casos/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAtlasIdRoute = AdminAtlasIdRouteImport.update({
  id: '/atlas/$id',
  path: '/atlas/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AppCasoIdRoute = AppCasoIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppCasoRoute,
} as any)
const AppAtlasRegionRoute = AppAtlasRegionRouteImport.update({
  id: '/$region',
  path: '/$region',
  getParentRoute: () => AppAtlasRoute,
} as any)
const AppAtlasRegionIndexRoute = AppAtlasRegionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAtlasRegionRoute,
} as any)
const AppAtlasRegionStructureRoute = AppAtlasRegionStructureRouteImport.update({
  id: '/$structure',
  path: '/$structure',
  getParentRoute: () => AppAtlasRegionRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/atlas': typeof AppAtlasRouteWithChildren
  '/caso': typeof AppCasoRouteWithChildren
  '/home': typeof AppHomeRoute
  '/perfil': typeof AppPerfilRoute
  '/quiz': typeof AppQuizRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/admin/': typeof AdminIndexRoute
  '/atlas/$region': typeof AppAtlasRegionRouteWithChildren
  '/caso/$id': typeof AppCasoIdRoute
  '/admin/atlas/$id': typeof AdminAtlasIdRoute
  '/admin/casos/$id': typeof AdminCasosIdRoute
  '/admin/quiz/$id': typeof AdminQuizIdRoute
  '/atlas/': typeof AppAtlasIndexRoute
  '/caso/': typeof AppCasoIndexRoute
  '/admin/atlas/': typeof AdminAtlasIndexRoute
  '/admin/casos/': typeof AdminCasosIndexRoute
  '/admin/quiz/': typeof AdminQuizIndexRoute
  '/atlas/$region/$structure': typeof AppAtlasRegionStructureRoute
  '/atlas/$region/': typeof AppAtlasRegionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/home': typeof AppHomeRoute
  '/perfil': typeof AppPerfilRoute
  '/quiz': typeof AppQuizRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/admin': typeof AdminIndexRoute
  '/caso/$id': typeof AppCasoIdRoute
  '/admin/atlas/$id': typeof AdminAtlasIdRoute
  '/admin/casos/$id': typeof AdminCasosIdRoute
  '/admin/quiz/$id': typeof AdminQuizIdRoute
  '/atlas': typeof AppAtlasIndexRoute
  '/caso': typeof AppCasoIndexRoute
  '/admin/atlas': typeof AdminAtlasIndexRoute
  '/admin/casos': typeof AdminCasosIndexRoute
  '/admin/quiz': typeof AdminQuizIndexRoute
  '/atlas/$region/$structure': typeof AppAtlasRegionStructureRoute
  '/atlas/$region': typeof AppAtlasRegionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/_app/atlas': typeof AppAtlasRouteWithChildren
  '/_app/caso': typeof AppCasoRouteWithChildren
  '/_app/home': typeof AppHomeRoute
  '/_app/perfil': typeof AppPerfilRoute
  '/_app/quiz': typeof AppQuizRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/admin/': typeof AdminIndexRoute
  '/_app/atlas/$region': typeof AppAtlasRegionRouteWithChildren
  '/_app/caso/$id': typeof AppCasoIdRoute
  '/admin/atlas/$id': typeof AdminAtlasIdRoute
  '/admin/casos/$id': typeof AdminCasosIdRoute
  '/admin/quiz/$id': typeof AdminQuizIdRoute
  '/_app/atlas/': typeof AppAtlasIndexRoute
  '/_app/caso/': typeof AppCasoIndexRoute
  '/admin/atlas/': typeof AdminAtlasIndexRoute
  '/admin/casos/': typeof AdminCasosIndexRoute
  '/admin/quiz/': typeof AdminQuizIndexRoute
  '/_app/atlas/$region/$structure': typeof AppAtlasRegionStructureRoute
  '/_app/atlas/$region/': typeof AppAtlasRegionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/onboarding'
    | '/atlas'
    | '/caso'
    | '/home'
    | '/perfil'
    | '/quiz'
    | '/auth/callback'
    | '/admin/'
    | '/atlas/$region'
    | '/caso/$id'
    | '/admin/atlas/$id'
    | '/admin/casos/$id'
    | '/admin/quiz/$id'
    | '/atlas/'
    | '/caso/'
    | '/admin/atlas/'
    | '/admin/casos/'
    | '/admin/quiz/'
    | '/atlas/$region/$structure'
    | '/atlas/$region/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/home'
    | '/perfil'
    | '/quiz'
    | '/auth/callback'
    | '/admin'
    | '/caso/$id'
    | '/admin/atlas/$id'
    | '/admin/casos/$id'
    | '/admin/quiz/$id'
    | '/atlas'
    | '/caso'
    | '/admin/atlas'
    | '/admin/casos'
    | '/admin/quiz'
    | '/atlas/$region/$structure'
    | '/atlas/$region'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/admin'
    | '/login'
    | '/onboarding'
    | '/_app/atlas'
    | '/_app/caso'
    | '/_app/home'
    | '/_app/perfil'
    | '/_app/quiz'
    | '/auth/callback'
    | '/admin/'
    | '/_app/atlas/$region'
    | '/_app/caso/$id'
    | '/admin/atlas/$id'
    | '/admin/casos/$id'
    | '/admin/quiz/$id'
    | '/_app/atlas/'
    | '/_app/caso/'
    | '/admin/atlas/'
    | '/admin/casos/'
    | '/admin/quiz/'
    | '/_app/atlas/$region/$structure'
    | '/_app/atlas/$region/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/quiz': {
      id: '/_app/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof AppQuizRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/perfil': {
      id: '/_app/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/caso': {
      id: '/_app/caso'
      path: '/caso'
      fullPath: '/caso'
      preLoaderRoute: typeof AppCasoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/atlas': {
      id: '/_app/atlas'
      path: '/atlas'
      fullPath: '/atlas'
      preLoaderRoute: typeof AppAtlasRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/quiz/': {
      id: '/admin/quiz/'
      path: '/quiz'
      fullPath: '/admin/quiz/'
      preLoaderRoute: typeof AdminQuizIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/casos/': {
      id: '/admin/casos/'
      path: '/casos'
      fullPath: '/admin/casos/'
      preLoaderRoute: typeof AdminCasosIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/atlas/': {
      id: '/admin/atlas/'
      path: '/atlas'
      fullPath: '/admin/atlas/'
      preLoaderRoute: typeof AdminAtlasIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/caso/': {
      id: '/_app/caso/'
      path: '/'
      fullPath: '/caso/'
      preLoaderRoute: typeof AppCasoIndexRouteImport
      parentRoute: typeof AppCasoRoute
    }
    '/_app/atlas/': {
      id: '/_app/atlas/'
      path: '/'
      fullPath: '/atlas/'
      preLoaderRoute: typeof AppAtlasIndexRouteImport
      parentRoute: typeof AppAtlasRoute
    }
    '/admin/quiz/$id': {
      id: '/admin/quiz/$id'
      path: '/quiz/$id'
      fullPath: '/admin/quiz/$id'
      preLoaderRoute: typeof AdminQuizIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/casos/$id': {
      id: '/admin/casos/$id'
      path: '/casos/$id'
      fullPath: '/admin/casos/$id'
      preLoaderRoute: typeof AdminCasosIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/atlas/$id': {
      id: '/admin/atlas/$id'
      path: '/atlas/$id'
      fullPath: '/admin/atlas/$id'
      preLoaderRoute: typeof AdminAtlasIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/caso/$id': {
      id: '/_app/caso/$id'
      path: '/$id'
      fullPath: '/caso/$id'
      preLoaderRoute: typeof AppCasoIdRouteImport
      parentRoute: typeof AppCasoRoute
    }
    '/_app/atlas/$region': {
      id: '/_app/atlas/$region'
      path: '/$region'
      fullPath: '/atlas/$region'
      preLoaderRoute: typeof AppAtlasRegionRouteImport
      parentRoute: typeof AppAtlasRoute
    }
    '/_app/atlas/$region/': {
      id: '/_app/atlas/$region/'
      path: '/'
      fullPath: '/atlas/$region/'
      preLoaderRoute: typeof AppAtlasRegionIndexRouteImport
      parentRoute: typeof AppAtlasRegionRoute
    }
    '/_app/atlas/$region/$structure': {
      id: '/_app/atlas/$region/$structure'
      path: '/$structure'
      fullPath: '/atlas/$region/$structure'
      preLoaderRoute: typeof AppAtlasRegionStructureRouteImport
      parentRoute: typeof AppAtlasRegionRoute
    }
  }
}

interface AppAtlasRegionRouteChildren {
  AppAtlasRegionStructureRoute: typeof AppAtlasRegionStructureRoute
  AppAtlasRegionIndexRoute: typeof AppAtlasRegionIndexRoute
}

const AppAtlasRegionRouteChildren: AppAtlasRegionRouteChildren = {
  AppAtlasRegionStructureRoute: AppAtlasRegionStructureRoute,
  AppAtlasRegionIndexRoute: AppAtlasRegionIndexRoute,
}

const AppAtlasRegionRouteWithChildren = AppAtlasRegionRoute._addFileChildren(
  AppAtlasRegionRouteChildren,
)

interface AppAtlasRouteChildren {
  AppAtlasRegionRoute: typeof AppAtlasRegionRouteWithChildren
  AppAtlasIndexRoute: typeof AppAtlasIndexRoute
}

const AppAtlasRouteChildren: AppAtlasRouteChildren = {
  AppAtlasRegionRoute: AppAtlasRegionRouteWithChildren,
  AppAtlasIndexRoute: AppAtlasIndexRoute,
}

const AppAtlasRouteWithChildren = AppAtlasRoute._addFileChildren(
  AppAtlasRouteChildren,
)

interface AppCasoRouteChildren {
  AppCasoIdRoute: typeof AppCasoIdRoute
  AppCasoIndexRoute: typeof AppCasoIndexRoute
}

const AppCasoRouteChildren: AppCasoRouteChildren = {
  AppCasoIdRoute: AppCasoIdRoute,
  AppCasoIndexRoute: AppCasoIndexRoute,
}

const AppCasoRouteWithChildren =
  AppCasoRoute._addFileChildren(AppCasoRouteChildren)

interface AppRouteChildren {
  AppAtlasRoute: typeof AppAtlasRouteWithChildren
  AppCasoRoute: typeof AppCasoRouteWithChildren
  AppHomeRoute: typeof AppHomeRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppQuizRoute: typeof AppQuizRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAtlasRoute: AppAtlasRouteWithChildren,
  AppCasoRoute: AppCasoRouteWithChildren,
  AppHomeRoute: AppHomeRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppQuizRoute: AppQuizRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAtlasIdRoute: typeof AdminAtlasIdRoute
  AdminCasosIdRoute: typeof AdminCasosIdRoute
  AdminQuizIdRoute: typeof AdminQuizIdRoute
  AdminAtlasIndexRoute: typeof AdminAtlasIndexRoute
  AdminCasosIndexRoute: typeof AdminCasosIndexRoute
  AdminQuizIndexRoute: typeof AdminQuizIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminAtlasIdRoute: AdminAtlasIdRoute,
  AdminCasosIdRoute: AdminCasosIdRoute,
  AdminQuizIdRoute: AdminQuizIdRoute,
  AdminAtlasIndexRoute: AdminAtlasIndexRoute,
  AdminCasosIndexRoute: AdminCasosIndexRoute,
  AdminQuizIndexRoute: AdminQuizIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
